-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:47:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Venda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Venda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Venda` DEFAULT CHARACTER SET utf8 ;
USE `Venda` ;

-- -----------------------------------------------------
-- Table `Venda`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venda`.`CATEGORIA` (
  `idcategoria` 			INT NOT NULL,
  `dscategoria` 			VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Venda`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venda`.`PRODUTO` (
  `idproduto` 				 INT NOT NULL,
  `dsproduto` 				 VARCHAR(45) NOT NULL,
  `peco` 					 FLOAT NOT NULL,
  `qtdade` 			 		 INT NOT NULL,
  `foto`  					 LONGBLOB NOT NULL,
  `CATEGORIA_idcategoria`    INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  -- INDEX `fk_PRODUTO_CATEGORIA_idx` (`CATEGORIA_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_CATEGORIA`
    FOREIGN KEY (`CATEGORIA_idcategoria`)
    REFERENCES `Venda`.`CATEGORIA` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Venda`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venda`.`CLIENTE` (
  `idcliente` 				 INT NOT NULL,
  `nome` VARCHAR(100) 		 NOT NULL,
  `email` VARCHAR(100) 		 NOT NULL,
  `senha` VARCHAR(100) 	     NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Venda`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venda`.`PEDIDO` (
  `idpedido` 				 INT NOT NULL,
  `data` 					 DATE NOT NULL,
  `satatus` 				 VARCHAR(45) NOT NULL,
  `sessao` 					 VARCHAR(45) NOT NULL,
  `CLIENTE_idcliente` 		 INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  -- INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idcliente`)
    REFERENCES `Venda`.`CLIENTE` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Venda`.`PEDIDOITENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venda`.`PEDIDOITENS` (
  `idpedidoitens` 			 	INT NOT NULL,
  `qtdade` 						INT NOT NULL,
  `peco` 						FLOAT NOT NULL,
  `total` 						FLOAT NOT NULL,
  `PRODUTO_idproduto` 			INT NOT NULL,
  `PEDIDO_idpedido` 			INT NOT NULL,
  PRIMARY KEY (`idpedidoitens`),
  -- INDEX `fk_PEDIDOITENS_PRODUTO1_idx` (`PRODUTO_idproduto` ASC) VISIBLE,
  -- INDEX `fk_PEDIDOITENS_PEDIDO1_idx` (`PEDIDO_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOITENS_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idproduto`)
    REFERENCES `Venda`.`PRODUTO` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOITENS_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idpedido`)
    REFERENCES `Venda`.`PEDIDO` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
